import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
from pathlib import Path

import matplotlib.font_manager as font_manager
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.colors import PowerNorm
import matplotlib.ticker as mticker

# ---------- Paste your LaTeX table here ----------
# The content of this table is generated by make_table_from_log.py
LATEX_TABLE = r"""
\begin{table}
\centering
\caption{Cross-data evaluation results showing NME$\pm$STD for all train--test combinations across four datasets (FP, HC18, UCL, MULTI-CENTRE) and three anatomies. NME is unitless (measurement error normalised by inter-landmark distance; scale-invariant). Multi-centre models are trained on combined multi-centre data. Within each \emph{training dataset block} and for each biometric measurement, \textbf{bold} indicates the best (lowest) NME across the test datasets in that block and \underline{underline} indicates the second-best.}
\label{tab:cross_validation}
\begin{tabular}{|c|c|c|c|c|c|c|}
\hline
\multirow{3}{*}{\textbf{Train}} & \multirow{3}{*}{\textbf{Test}} & \multicolumn{5}{c|}{\textbf{NME $\pm$ STD}} \\
\cline{3-7}
 &  & \multicolumn{2}{c|}{\textbf{Head}} & \multicolumn{2}{c|}{\textbf{Abdomen}} & \textbf{Femur} \\
\cline{3-7}
 &  & \textbf{BPD} & \textbf{OFD} & \textbf{APAD} & \textbf{TAD} & \textbf{FL} \\
\hline
\multirow{4}{*}{FP} & FP
& \textbf{0.03$\pm$0.06} & \textbf{0.03$\pm$0.05} & \textbf{0.08$\pm$0.06} & \textbf{0.08$\pm$0.06} & \textbf{0.03$\pm$0.11} \\
\cline{2-7}
& HC18
& 0.08$\pm$0.12 & 0.08$\pm$0.13 &  &  &  \\
\cline{2-7}
& UCL
& 0.38$\pm$0.26 & 0.22$\pm$0.22 & 0.31$\pm$0.23 & 0.45$\pm$0.28 & 0.90$\pm$0.54 \\
\cline{2-7}
& MULTICENTRE
& \underline{0.06$\pm$0.14} & \underline{0.05$\pm$0.10} & \underline{0.13$\pm$0.15} & \underline{0.16$\pm$0.21} & \underline{0.12$\pm$0.34} \\
\hline
\multirow{4}{*}{HC18} & FP
& \underline{0.06$\pm$0.07} & \underline{0.06$\pm$0.07} &  &  &  \\
\cline{2-7}
& HC18
& \textbf{0.05$\pm$0.09} & \textbf{0.04$\pm$0.08} &  &  &  \\
\cline{2-7}
& UCL
& 0.15$\pm$0.16 & 0.19$\pm$0.23 &  &  &  \\
\cline{2-7}
& MULTICENTRE
& 0.06$\pm$0.11 & 0.07$\pm$0.11 &  &  &  \\
\hline
\multirow{4}{*}{UCL} & FP
& \underline{0.10$\pm$0.11} & \underline{0.09$\pm$0.09} & 0.17$\pm$0.13 & 0.16$\pm$0.12 & 0.07$\pm$0.18 \\
\cline{2-7}
& HC18
& 0.17$\pm$0.25 & 0.13$\pm$0.16 &  &  &  \\
\cline{2-7}
& UCL
& \textbf{0.08$\pm$0.18} & \textbf{0.05$\pm$0.11} & \textbf{0.08$\pm$0.14} & \textbf{0.08$\pm$0.14} & \textbf{0.02$\pm$0.03} \\
\cline{2-7}
& MULTICENTRE
& 0.12$\pm$0.17 & 0.10$\pm$0.12 & \underline{0.15$\pm$0.14} & \underline{0.14$\pm$0.13} & \underline{0.06$\pm$0.17} \\
\hline
\multirow{4}{*}{MULTICENTRE} & FP
& \underline{0.03$\pm$0.05} & \textbf{0.03$\pm$0.04} & 0.08$\pm$0.06 & 0.09$\pm$0.07 & 0.03$\pm$0.10 \\
\cline{2-7}
& HC18
& 0.05$\pm$0.08 & 0.04$\pm$0.07 &  &  &  \\
\cline{2-7}
& UCL
& \textbf{0.02$\pm$0.02} & \underline{0.03$\pm$0.11} & \textbf{0.05$\pm$0.12} & \textbf{0.05$\pm$0.12} & \textbf{0.01$\pm$0.01} \\
\cline{2-7}
& MULTICENTRE
& 0.04$\pm$0.07 & 0.03$\pm$0.06 & \underline{0.07$\pm$0.08} & \underline{0.08$\pm$0.08} & \underline{0.03$\pm$0.09} \\
\hline
\end{tabular}
\end{table}
"""
# ----------------------------------------------

# -------------------- Parsing helpers --------------------

def _clean_cell(cell):
    if cell is None:
        return ""
    s = cell.strip()
    # remove formatting commands repeatedly in case nested
    while True:
        s2 = re.sub(r"\\textbf\{([^{}]*)\}", r"\1", s)
        s2 = re.sub(r"\\underline\{([^{}]*)\}", r"\1", s2)
        if s2 == s:
            break
        s = s2
    # remove trailing LaTeX line breaks
    s = s.replace(r"\\", "").strip()
    return s


def _parse_mean_std(cell):
    """
    Parse cells like: 0.03$\pm$0.06 -> (0.03, 0.06)
    Returns (np.nan, np.nan) if empty/unparseable.
    """
    s = _clean_cell(cell)
    if not s:
        return (np.nan, np.nan)
    m = re.search(
        r"([0-9]+(?:\.[0-9]+)?)\s*\$\s*\\pm\s*\$\s*([0-9]+(?:\.[0-9]+)?)",
        s
    )
    if not m:
        return (np.nan, np.nan)
    return (float(m.group(1)), float(m.group(2)))


def _iter_latex_rows(latex):
    """
    Yield logical tabular rows by splitting on '\\\\' (row terminator),
    so rows spanning multiple physical lines still parse correctly.
    """
    m = re.search(r"\\begin\{tabular\}\{[^}]*\}(.*?)\\end\{tabular\}", latex, flags=re.S)
    body = m.group(1) if m else latex

    body = re.sub(r"\\hline", "", body)
    body = re.sub(r"\\cline\{[^}]*\}", "", body)

    for chunk in re.split(r"\\\\", body):
        row = chunk.strip()
        if row and ("&" in row):
            yield row


def parse_cross_eval_latex_table(latex):
    allowed = {"FP", "HC18", "UCL", "MULTICENTRE", "MULTI-CENTRE"}

    def norm_ds(x):
        x = _clean_cell(x).upper().replace(" ", "")
        if x in {"MULTI-CENTRE", "MULTICENTRE", "MULTI_CENTRE", "MULTICENTER"}:
            return "MULTICENTRE"
        return x

    allowed_norm = {norm_ds(a) for a in allowed}

    rows = []
    current_train = None

    for row in _iter_latex_rows(latex):
        cells = [c.strip() for c in row.split("&")]
        if len(cells) < 7:
            continue

        train_cell, test_cell = cells[0], cells[1]

        if r"\multirow" in train_cell:
            m = re.search(r"\\multirow\{\d+\}\{\*\}\{([^}]*)\}", train_cell)
            if not m:
                continue
            current_train = norm_ds(m.group(1))
            test = norm_ds(test_cell)
        else:
            if _clean_cell(train_cell) != "":
                continue  # header/junk
            if current_train is None:
                continue
            test = norm_ds(test_cell)

        train = current_train
        if train not in allowed_norm or test not in allowed_norm:
            continue

        metric_cells = cells[2:7]
        bpd_m, bpd_s = _parse_mean_std(metric_cells[0])
        ofd_m, ofd_s = _parse_mean_std(metric_cells[1])
        apad_m, apad_s = _parse_mean_std(metric_cells[2])
        tad_m, tad_s = _parse_mean_std(metric_cells[3])
        fl_m, fl_s = _parse_mean_std(metric_cells[4])

        rows.append({
            "train_ds": train, "test_ds": test,
            "BPD_mean": bpd_m, "BPD_std": bpd_s,
            "OFD_mean": ofd_m, "OFD_std": ofd_s,
            "APAD_mean": apad_m, "APAD_std": apad_s,
            "TAD_mean": tad_m, "TAD_std": tad_s,
            "FL_mean": fl_m, "FL_std": fl_s,
        })

    return pd.DataFrame(
        rows,
        columns=[
            "train_ds","test_ds",
            "BPD_mean","BPD_std",
            "OFD_mean","OFD_std",
            "APAD_mean","APAD_std",
            "TAD_mean","TAD_std",
            "FL_mean","FL_std",
        ],
    )


# -------------------- Styling (fonts + cmap) --------------------

SCRIPT_DIR = Path(__file__).resolve().parent

def setup_fonts():
    # Lato first, DejaVu Sans fallback to avoid missing glyphs
    try:
        font_dir = SCRIPT_DIR / "fonts" / "Lato"
        if font_dir.exists():
            for ff in font_manager.findSystemFonts(fontpaths=str(font_dir)):
                font_manager.fontManager.addfont(ff)

            plt.rcParams["font.family"] = "sans-serif"
            plt.rcParams["font.sans-serif"] = ["Lato", "DejaVu Sans"]
        else:
            print("Lato folder not found at:", font_dir)
    except Exception as e:
        print("Lato font registration failed, using default font. Error:", e)

    # Keep text as text in SVG
    plt.rcParams["svg.fonttype"] = "none"

    # Optional figure text styling
    plt.rcParams["font.size"] = 14
    plt.rcParams["axes.titleweight"] = "bold"
    plt.rcParams["axes.labelweight"] = "bold"


CUSTOM_CMAP = LinearSegmentedColormap.from_list(
    "custom_bluegray",
    ["#02446e", "#3f6d85", "#4996a8", "#a2c3ca", "#d1e0e3", "#E6E6E6"],
    N=256,
)


# -------------------- Matrix building --------------------

def make_metric_matrices_from_table(df, datasets_order_by_metric):
    mats = {}
    for metric_col, order in datasets_order_by_metric.items():
        mat = df.pivot_table(index="train_ds", columns="test_ds", values=metric_col, aggfunc="mean")
        mats[metric_col] = mat.reindex(index=order, columns=order)
    return mats


# -------------------- Scaling utilities --------------------

def _finite_vals(*mats):
    vals = []
    for mat in mats:
        a = mat.values.astype(float).ravel()
        a = a[~np.isnan(a)]
        vals.append(a)
    if not vals:
        return np.array([], dtype=float)
    return np.concatenate(vals) if len(vals) > 1 else vals[0]


def compute_group_scales(metric_mats, groups, clip_percentiles=(5, 95)):
    """
    groups: dict[group_name] = list of metric keys (e.g. ["BPD_mean","OFD_mean"])
    returns dict[group_name] = (vmin, vmax)
    """
    out = {}
    for gname, keys in groups.items():
        mats = [metric_mats[k] for k in keys if k in metric_mats]
        v = _finite_vals(*mats)
        if v.size == 0:
            out[gname] = (None, None)
            continue

        if clip_percentiles is None:
            vmin, vmax = float(np.min(v)), float(np.max(v))
        else:
            lo, hi = clip_percentiles
            vmin, vmax = np.percentile(v, [lo, hi]).astype(float)

        # safety against degenerate scales
        if not np.isfinite(vmin) or not np.isfinite(vmax):
            out[gname] = (None, None)
            continue
        if vmin == vmax:
            # expand slightly so imshow doesn't complain
            eps = 1e-6 if vmin == 0 else abs(vmin) * 1e-3
            vmin, vmax = vmin - eps, vmax + eps

        out[gname] = (vmin, vmax)
    return out


# -------------------- Plotting --------------------

def _heatmap(ax, mat, title, cmap, fmt="{:.2f}", vmin=None, vmax=None, norm=None, cbar_decimals=3):
    arr = mat.values.astype(float)

    # If norm is provided, don't pass vmin/vmax separately unless you embed them in norm.
    if norm is None:
        im = ax.imshow(arr, aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax)
    else:
        im = ax.imshow(arr, aspect="auto", cmap=cmap, norm=norm)

    ax.set_title(title)
    ax.set_xticks(range(mat.shape[1]))
    ax.set_yticks(range(mat.shape[0]))
    ax.set_xticklabels(list(mat.columns), rotation=45, ha="right")
    ax.set_yticklabels(list(mat.index), rotation=45, ha="right")

    # annotate
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            v = mat.iat[i, j]
            txt = "NA" if pd.isna(v) else fmt.format(float(v))
            ax.text(j, i, txt, ha="center", va="center", fontsize=14)

    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.ax.yaxis.set_major_formatter(mticker.FormatStrFormatter(f'%.{cbar_decimals}f'))

def plot_metric_matrices_shared_by_group(
    metric_mats,
    cmap,
    save_prefix=None,
    clip_percentiles=(5, 95),
    use_power_norm=False,
    power_gamma=0.6,
):
    pretty = {
        "BPD_mean": "Head: BPD",
        "OFD_mean": "Head: OFD",
        "APAD_mean": "Abdomen: APAD",
        "TAD_mean": "Abdomen: TAD",
        "FL_mean": "Femur: FL",
    }

    metric_order = ["BPD_mean", "OFD_mean", "APAD_mean", "TAD_mean", "FL_mean"]

    # Anatomy groups for shared scaling
    groups = {
        "Head": ["BPD_mean", "OFD_mean"],
        "Abdomen": ["APAD_mean", "TAD_mean"],
        "Femur": ["FL_mean"],
    }
    group_scales = compute_group_scales(metric_mats, groups, clip_percentiles=clip_percentiles)

    # Map metric -> group
    metric_to_group = {}
    for g, keys in groups.items():
        for k in keys:
            metric_to_group[k] = g

    fig, axes = plt.subplots(2, 3, figsize=(18, 10), constrained_layout=True)
    axes = axes.ravel()

    for k, metric_col in enumerate(metric_order):
        ax = axes[k]
        mat = metric_mats[metric_col]
        g = metric_to_group[metric_col]
        vmin, vmax = group_scales[g]

        title = "Train -> Test NME (mean): {}".format(pretty.get(metric_col, metric_col))

        if use_power_norm and (vmin is not None) and (vmax is not None):
            # PowerNorm expects vmin/vmax embedded in the norm
            norm = PowerNorm(gamma=power_gamma, vmin=vmin, vmax=vmax)
            _heatmap(ax, mat, title, cmap=cmap, fmt="{:.2f}", norm=norm)
        else:
            _heatmap(ax, mat, title, cmap=cmap, fmt="{:.2f}", vmin=vmin, vmax=vmax, norm=None)

    axes[-1].axis("off")

    if save_prefix:
        fig.savefig(save_prefix + "_metrics.png", dpi=300, bbox_inches="tight")
        fig.savefig(save_prefix + "_metrics.svg", bbox_inches="tight")

    plt.show()


# -------------------- Main --------------------

if __name__ == "__main__":
    setup_fonts()

    df = parse_cross_eval_latex_table(LATEX_TABLE)
    print("Parsed rows:", len(df))
    if len(df) == 0:
        raise RuntimeError("Parsed 0 rows. Parser did not find any dataset rows in LATEX_TABLE.")

    # Dataset orders:
    datasets_order_head = ["FP", "HC18", "UCL", "MULTICENTRE"]
    datasets_order_no_hc18 = ["FP", "UCL", "MULTICENTRE"]

    datasets_order_by_metric = {
        "BPD_mean": datasets_order_head,
        "OFD_mean": datasets_order_head,
        "APAD_mean": datasets_order_no_hc18,
        "TAD_mean": datasets_order_no_hc18,
        "FL_mean":  datasets_order_no_hc18,
    }

    metric_mats = make_metric_matrices_from_table(df, datasets_order_by_metric)

    # Shared scale per anatomy group (Head / Abdomen / Femur), with percentile clipping
    plot_metric_matrices_shared_by_group(
        metric_mats,
        cmap=CUSTOM_CMAP,
        save_prefix="cross_data",
        clip_percentiles=(5, 95),   # set to None for strict min/max
        use_power_norm=False,       # try True if you *really* want more contrast
        power_gamma=0.6,
    )